---
kind: pipeline
type: docker
name: test

steps:
  - name: testing
    image: alpine/git
    commands: 
      - echo "oi"
      - git tag -f -a vaca -m "hehehehe"
trigger:
  event:
    - push
    - pull_request
# kind: pipeline
# type: docker
# name: production

# steps:
#   - name: sending_to_prod
#     image: alpine
#     commands:
#       - apk add --no-cache git
#       - echo "DEPLOY TO PRODUCTION"
#       - echo "parent build ${DRONE_BUILD_PARENT}"
#       - echo "we're deploying to ${DRONE_DEPLOY_TO}"
#       - echo "current branch [ $(git branch) ]"
#       - >- 
#         git checkout $DRONE_DEPLOY_TO
#         PREVIOUS_MASTER=$(git rev-list -n 1 ${DRONE_DEPLOY_TO})
#         echo "PREVIOUS MASTER [ $PREVIOUS_MASTER ]"

# trigger:
#   event:
#     - promote
#     - push
#     - pull_request
#   branches:
#     - production
#   target:
#     - production
# ---
# kind: pipeline
# type: docker
# name: stagin

# steps:
#   - name: sending_to_stage
#     image: alpine
#     commands:
#       - echo "DEPLOY TO stage"

# trigger:
#   event:
#     - promote
#     - push
#     - pull_request
#   branches:
#     - stage
#   target:
#     - stage
# ---
# kind: pipeline
# type: docker
# name: tag-changes

# trigger:
#   event:
#     - tag

# steps:
#   - name: on-tags-changes
#     image: alpine
#     commands:
#       - echo "tags changes"
# ---
# kind: pipeline
# type: docker
# name: util pipeline A

# steps:
#   - name: PREF a
#     image: alpine
#     commands:
#       - echo "A"
# ---
# kind: pipeline
# type: docker
# name: util pipeline B

# steps:
#   - name: PREF b
#     image: alpine
#     commands:
#       - echo "B"
#       - sleep 9
# ---
# kind: pipeline
# type: docker
# name: tag pipeline

# steps:
#   - name: tagging stuff
#     image: animal505/ffff
#     pull: always
#     settings:
#       DRONE_BUILD_STATUS: ${DRONE_BUILD_STATUS}
---
kind: pipeline
name: "tagging promotion environment"
type: kubernetes
node_selector:
  component: ci-runners 
steps:
  - name: Log
    image: alpine
    commands:
      - echo "branch ${DRONE_BRANCH}"
      - echo "tagging promotion environment [ ${DRONE_DEPLOY_TO} ]"
  - name: fetch and checkout branch
    image: alpine/git
    commands:
      - git fetch origin "${DRONE_BRANCH}"
      - git checkout -B "${DRONE_BRANCH}" "origin/${DRONE_BRANCH}"
  - name: tag current branch and push
    image: alpine/git
    commands:
      - git tag -f -a "${DRONE_DEPLOY_TO}_test" -m "creating new tag for environment ${DRONE_DEPLOY_TO}"
    environment:
      CICD_BOT_TOKEN:
        from_secret: CICD_BOT_TOKEN
      GIT_AUTHOR_EMAIL: sysadmins+gitlab-iac-cicd-bot@postclick.com
      GIT_AUTHOR_NAME: "IaC CI/CD Bot"
      GIT_COMMITTER_EMAIL: sysadmins+gitlab-iac-cicd-bot@postclick.com
      GIT_COMMITTER_NAME: "IaC CI/CD Bot"

trigger:
  # branch:
  #   - master
  event:
    - promote
  #   - pull_request
  target:
    - production
  
