kind: pipeline
name: validating
type: kubernetes
clone:
  disable: false
steps:
  - name: validating
    image: alpine
    commands:
      - echo "talkey moral"
trigger:
  event:
    - promote
  target:
    - prod
    - pre-prod
---
kind: pipeline
name: prod
type: kubernetes
depends_on:
  - validating
steps:
  - name: prod log
    image: alpine
    commands:
      - echo "prod"
trigger:
  event:
    - promote
  target:
    - prod
---
kind: pipeline
name: pre-prod
type: kubernetes
depends_on:
  - validating
steps:
  - name: pre-prod log
    image: alpine
    commands:
      - echo "pre-prod"
trigger:
  event:
    - promote
  target:
    - pre-prod
---
kind: pipeline
name: saving point
type: kubernetes
depends_on:
  - pre-prod
  - prod
steps:
  - name: log
    image: alpine
    commands:
      - echo "hi lorena"
trigger:
  event:
    - promote
  target:
    - pre-prod
    - prod
---
kind: pipeline
type: docker
name: test

steps:
  - name: lets
    image: alpine
    pull: always
    commands:
      - /bin/sh run.sh 
  - name: using plugin
    image: animal505/piru
    pull: always
    settings:
      packages_to_promote_file_path: my-file.txt


trigger:
  event:
    - push
    - pull_request

# kind: pipeline
# type: docker
# name: production

# steps:
#   - name: sending_to_prod
#     image: alpine
#     commands:
#       - apk add --no-cache git
#       - echo "DEPLOY TO PRODUCTION"
#       - echo "parent build ${DRONE_BUILD_PARENT}"
#       - echo "we're deploying to ${DRONE_DEPLOY_TO}"
#       - echo "current branch [ $(git branch) ]"
#       - >- 
#         git checkout $DRONE_DEPLOY_TO
#         PREVIOUS_MASTER=$(git rev-list -n 1 ${DRONE_DEPLOY_TO})
#         echo "PREVIOUS MASTER [ $PREVIOUS_MASTER ]"

# trigger:
#   event:
#     - promote
#     - push
#     - pull_request
#   branches:
#     - production
#   target:
#     - production
# ---
# kind: pipeline
# type: docker
# name: stagin

# steps:
#   - name: sending_to_stage
#     image: alpine
#     commands:
#       - echo "DEPLOY TO stage"

# trigger:
#   event:
#     - promote
#     - push
#     - pull_request
#   branches:
#     - stage
#   target:
#     - stage
# ---
# kind: pipeline
# type: docker
# name: tag-changes

# trigger:
#   event:
#     - tag

# steps:
#   - name: on-tags-changes
#     image: alpine
#     commands:
#       - echo "tags changes"
# ---
# kind: pipeline
# type: docker
# name: util pipeline A

# steps:
#   - name: PREF a
#     image: alpine
#     commands:
#       - echo "A"
# ---
# kind: pipeline
# type: docker
# name: util pipeline B

# steps:
#   - name: PREF b
#     image: alpine
#     commands:
#       - echo "B"
#       - sleep 9
# ---
# kind: pipeline
# type: docker
# name: tag pipeline

# steps:
#   - name: tagging stuff
#     image: animal505/ffff
#     pull: always
#     settings:
#       DRONE_BUILD_STATUS: ${DRONE_BUILD_STATUS}

