---
kind: pipeline
type: docker
name: test

steps:
  - name: testing
    image: alpine
    commands: 
      - echo "oi"
trigger:
  event:
    - push
    - pull_request

---
kind: pipeline
type: docker
name: production

steps:
  - name: sending_to_prod
    image: alpine
    commands:
      - apk add --no-cache git
      - echo "DEPLOY TO PRODUCTION"
      - echo "parent build ${DRONE_BUILD_PARENT}"
      - echo "we're deploying to ${DRONE_DEPLOY_TO}"
      - >- 
        PREVIOUS_MASTER=$(git rev-list -n 1 ${DRONE_DEPLOY_TO})
        echo "PREVIOUS MASTER $PREVIOUS_MASTER"

trigger:
  event:
    - promote
    - push
    - pull_request
  branches:
    - production
  target:
    - production
---
kind: pipeline
type: docker
name: stagin

steps:
  - name: sending_to_stage
    image: alpine
    commands:
      - echo "DEPLOY TO stage"

trigger:
  event:
    - promote
    - push
    - pull_request
  branches:
    - stage
  target:
    - stage
---
kind: pipeline
type: docker
name: tag-changes

trigger:
  event:
    - tag

steps:
  - name: on-tags-changes
    image: alpine
    commands:
      - echo "tags changes"
